package model.common.constaint;

public enum MonsterType { DRAGON, MAGICIAN, ROBOT, WARRIOR,
    BEAST, FAIRY, AQUATIC, DINOSAUR, REPTILE, INSECT, PLANT,
    ROCK, ZOMBIE, SPELLCASTER, CYBERSE, MACHINE, FISH,
    SEA_SERPENT, THUNDER, WINGED_BEAST, PYRO,
    AERIAL_BEAST, DIVINE_BEAST, UNKNOWN }